# Generated by Django 6.0.4 on 2026-04-21 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interaction',
            options={'ordering': ['-created_at']},
        ),
    ]
